### ISSUE TITLE
左侧侧边栏颜色与主题割裂

### ISSUE THREAD

**Issue by BaiMaollk** [SyrieYume/starrail_ui#1]
![image](https://github.com/SyrieYume/starrail_ui/assets/75015352/5f77e672-1a2c-447a-a4ea-07daa3cee52b)
左边侧边栏怎么隐藏

**Comment by BaiMaollk** [comment]
![image](https://github.com/SyrieYume/starrail_ui/assets/75015352/fb83e363-b788-475f-baed-321e3af49634)
插件装了这些

**Comment by SyrieYume** [comment]
这个插件可以隐藏左侧侧边栏： https://github.com/hacker-frok/LiteLoaderQQNT-Plugin-Brevity-btn

**Comment by BaiMaollk** [comment]
完美了，谢谢
