### ISSUE TITLE
[bug] 气泡无法正常切换

### ISSUE THREAD

**Issue by Wfgukasha** [SyrieYume/starrail_ui#10]
# 准备工作

- 我已经确认没有其他issue与我提出了同样的问题
- 我确认我所使用的插件是最新版
- 在只使用本插件的情况下,问题仍然存在

# 环境信息
![image](https://github.com/SyrieYume/starrail_ui/assets/162772997/8080be33-4b35-4d84-8742-d5cfa406c323)
- windows 10
 # 复现方法:
- 点击设置中的气泡切换,气泡未能按照预期切换
# 期望
设置的气泡能够正常切换
# 相关日志截图
![image](https://github.com/SyrieYume/starrail_ui/assets/162772997/578fe217-cf2c-4cff-99b6-43f6448fb1e3)
# 我安装的插件
- 轻量工具箱
- starrail_ui

**Comment by SyrieYume** [comment]
很抱歉，我在 Windows11 QQ 9.9.12-25234版本 中无法复现这个bug，有可能是QQ更新导致的，请你尝试回退QQ版本。
