### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by gaot654** [SyrieYume/starrail_ui#11]
系统设置改了字体大小，但未能生效。在UI界面无法修改字体大小

**Comment by SyrieYume** [comment]
> 系统设置改了字体大小，但未能生效。在UI界面无法修改字体大小

请问你说的“**系统设置改了字体大小**”是指在Windows系统的设置里修改了字体大小，还是指在 QQ设置 > 通用 里修改了字体大小？
如果是后者，确实存在这个问题。因为为了匹配气泡框的大小，字体大小设定为了固定值。
这个问题我会在下个版本修复。
