### ISSUE TITLE
暂时遇到的bug以及不太美观的问题(包含有关其他插件同时使用时出现的问题)

### ISSUE THREAD

**Issue by yhzcake** [SyrieYume/starrail_ui#12]
首先是插件本身的bug:
当消息背景透明度非初始值,导致的其他消息框含有非透明背景
![image](https://github.com/SyrieYume/starrail_ui/assets/80627671/2a9a2cfb-8399-44e5-8905-8fed397a77a9)
![image](https://github.com/SyrieYume/starrail_ui/assets/80627671/e0f3efe0-802c-48a1-8b50-c65e9d6c0639)
深色模式下浮动的控制栏颜色没变,但是我觉得也调成深色更契合一些
![image](https://github.com/SyrieYume/starrail_ui/assets/80627671/7298c788-76dd-479e-89f2-53668ad0a860)
白天模式下搜索栏的放大镜图标没正常显示,我认为这个是bug
![image](https://github.com/SyrieYume/starrail_ui/assets/80627671/efe55d03-2e49-409c-9714-5494a7bff8b1)
另外提个功能建议呗,能不能根据深色模式换背景图片?(一直没有做这个功能的...背景图片亮度最好也可以设置两个值)
背景插件被这个模组覆盖,同时安装时背景插件无效
其他插件附加的功能按键随深色模组改变svg颜色导致颜色不统一
![image](https://github.com/SyrieYume/starrail_ui/assets/80627671/47062e92-1d44-4f90-8089-bb8715cdeaf3)
![image](https://github.com/SyrieYume/starrail_ui/assets/80627671/62f4d2bd-ffd1-443e-b755-0daae42d9a92)
在使用轻量工具箱使自己消息靠左显示时无法正确渲染消息框
![image](https://github.com/SyrieYume/starrail_ui/assets/80627671/8dde8ca7-7091-45dd-bd91-e8a52a0d6241)
同时使用qq纯享模式插件时,样式不是很美观
![image](https://github.com/SyrieYume/starrail_ui/assets/80627671/d7cccb74-5f58-42b6-b8de-4fb389799ab0)
并且在这种情况下深色模式时也不显示放大镜图标
![image](https://github.com/SyrieYume/starrail_ui/assets/80627671/be7676b4-6138-4f43-aa46-7c688807a45d)

**Comment by yhzcake** [comment]
另外我发现撤回的字体不太对..
![image](https://github.com/SyrieYume/starrail_ui/assets/80627671/c4052656-9a75-4df3-9aea-d308b2c5a75e)

**Comment by SyrieYume** [comment]
这些都是其他插件引起的，我没办法适配每个插件。
