### ISSUE TITLE
希望添加对气泡和文字大小修改的支持

### ISSUE THREAD

**Issue by liudanT800** [SyrieYume/starrail_ui#13]
![屏幕截图 2024-07-06 161642](https://github.com/SyrieYume/starrail_ui/assets/82273342/c3f607e1-3ef8-476d-8db3-9b829fecd254)
![屏幕截图 2024-07-06 161754](https://github.com/SyrieYume/starrail_ui/assets/82273342/cdbb8c35-760b-400f-ab82-00b71cae96f5)
如题，在1080p小尺寸显示器下显示文本量感觉偏少了

**Comment by SyrieYume** [comment]
已经有人提过类似的问题。
如果你希望在1080p分辨率下显示更多内容，你应该调低Windows显示设置里的缩放。
