### ISSUE TITLE
希望能在“隐藏部分组件的背景色”部分添加.viewport-list__inner

### ISSUE THREAD

**Issue by raichuq** [SyrieYume/starrail_ui#14]
不知道是否是和 lite-tools 冲突或是其他插件冲突的影响，
白天模式下左侧消息列表的背景色仍为白色。
通过测试发现在 plugins\starrail_ui\src\style.css 中的“隐藏部分组件的背景色”部分添加 .viewport-list__inner 可以解决，让显示效果和预览图一致。
此外，还有联系人列表（.contact,.tab-header）、联系人详情（.tab-content,.q-collapse-item__header等)背景也是白色，不知是否是插件冲突所致。
![image](https://github.com/SyrieYume/starrail_ui/assets/14349350/66650b61-183a-465c-a01d-331d64f27cf2)

**Comment by SyrieYume** [comment]
可能是其它插件导致的，也可能是QQ更新导致的。至少在我目前的测试的版本(9.9.12-25234), .viewport-list__inner默认是没有背景色的。我会在后续更新中加上这个。
联系人列表这个界面，因为用的不多，我就懒得改了。要把这个界面背景色改成透明的话，还要考虑浅色背景和深色背景下字体颜色的问题，太麻烦了。

**Comment by raichuq** [comment]
> 可能是其它插件导致的，也可能是QQ更新导致的。至少在我目前的测试的版本(9.9.12-25234), .viewport-list__inner默认是没有背景色的。我会在后续更新中加上这个。 联系人列表这个界面，因为用的不多，我就懒得改了。要把这个界面背景色改成透明的话，还要考虑浅色背景和深色背景下字体颜色的问题，太麻烦了。

已确认为QQNT版本的问题，9.9.7更新至9.9.10后使用原style.css文件显示正常了。
