### ISSUE TITLE
是否会考虑增加头像大小的可自定义

### ISSUE THREAD

**Issue by Readedd** [SyrieYume/starrail_ui#2]
头像大小的自定义，消息列表和聊天界面元素的大小自定义，或者提供一个整体比例缩放的设置

**Comment by SyrieYume** [comment]
这个不太好加在设置项里，我在 0.1.1 版本中给 src/style.css 添加了注释，你可以根据需要自己修改。
比如你要改消息列表的头像大小，可以修改 style.css 第278行的 `--avatar_size_3`；要修改聊天界面的头像大小，就修改第130行的 `--avatar_size_2`。
修改并保存之后，重启QQ就行了。

**Comment by Readedd** [comment]
感谢
