### ISSUE TITLE
夜间模式下消息可读性差

### ISSUE THREAD

**Issue by nicklly** [SyrieYume/starrail_ui#20]
如图
![QQ_1721832265728](https://github.com/user-attachments/assets/c68f5924-695c-4df7-ad4c-3a137fff904b)
![QQ_1721832345836](https://github.com/user-attachments/assets/35664a0f-a1ef-451b-944e-b68c90e20b4c)

1、在夜间模式下，对方或群友发送的消息字体为黑色，与背景颜色高度重合
2、仿制的聊天气泡有边框

以上问题，作者大大是否可以考虑在下一版更新中修一下（）

**Comment by SyrieYume** [comment]
这个问题是其他插件导致的，和本插件无关。
请你自行排查出导致问题的插件。
