### ISSUE TITLE
适配新气泡

### ISSUE THREAD

**Issue by misaka10384** [SyrieYume/starrail_ui#21]
小三月这个气泡好看 
![e80cb82fc406ed5bc674fd33cb990ca8](https://github.com/user-attachments/assets/85dca212-1fcc-4ebc-a81c-201135990053)

**Comment by SyrieYume** [comment]
在最新版添加了这个气泡框：https://github.com/SyrieYume/starrail_ui/releases/tag/v0.2.1

**Comment by misaka10384** [comment]
> 在最新版添加了这个气泡框：https://github.com/SyrieYume/starrail_ui/releases/tag/v0.2.1

好耶  谢谢大佬
