### ISSUE TITLE
【元素调整】聊天窗口不透明度 在更低的值的情况下表现不佳

### ISSUE THREAD

**Issue by wawdili** [SyrieYume/starrail_ui#22]
如图所示：工具栏，回到底部，文本输入框和群名称的对比度可能不够高，这也许会导致阅读困难。
这些应该在低透明度的情况下调整为白色，或者留给用户自己调整。
在工具栏，回到底部添加叠加层，能有效增加边缘感，区分元素。

额外的，建议添加更多自定义项，例如右上角的更多工具自动隐藏，头像大小等（才注意到 :\ ）。

![31fddcdeb487f74aa42466879cfcdc37](https://github.com/user-attachments/assets/cba1db60-4ed9-467c-b2ac-cf891c800af8)

**Comment by SyrieYume** [comment]
设置里的不透明度本来就不是用来调到几乎全透明的，之所以有这一项，是因为星铁的短信背景有一点点透明度。
至于其它提议，你可以自行修改`style.css`文件，我不会将这些加到设置里，假如所有地方的样式都要求自定义，那设置页面就太乱了。
