### ISSUE TITLE
[期望]对某些插件进行适配

### ISSUE THREAD

**Issue by yhzcake** [SyrieYume/starrail_ui#23]
[https://github.com/PRO-2684/Transitio-user-css/issues/13](url)
一个是这里,具体情况参考链接里
一个是使用markdown-it时code中的字体颜色被本插件覆盖了,希望针对code的部分调整一下字体颜色
(虽然markdown这个插件的bug更离谱...所以这条可以当没看到,在这个插件完善之前我大概不会使用它...)
另外,针对本插件的某些修改,我制作了一个自认为还算美观的覆盖样式,可以使用Transitio加载
[sr_ui_extra.zip](https://github.com/user-attachments/files/16577405/sr_ui_extra.zip)

**Comment by SyrieYume** [comment]
1. 第一个问题，是因为，为了解决背景图加入 `filter: blur` 后边缘出现白边的问题，背景图元素的实际大小比窗口大10%。
   为了防止页面滚动，`#app>.container` 的 `overflow-y` 设置为了 `hidden` 。
   但是在粘贴大段内容时，Transition 的 平滑滚动 意外导致了文本框以外的地方发生滚动。
   解决方法就是，关闭 **Transition** 里的 **平滑滚动** 。
   顺带一提，**Transition** 的 **移除消息聚焦遮罩** 会移除掉气泡框 “光阴莫负” 的背景，这个也可以在Transition的设置项里关闭。
2. 第二个问题，是因为消息文本里`span`的样式被覆盖了，而markdown-it插件`code`中的内容也是`span`, 这个我可以在下版本调整一下。

**Comment by yhzcake** [comment]
了解了,多谢
