### ISSUE TITLE
[建议] 建议新增调整消息缩放大小的功能

### ISSUE THREAD

**Issue by AmzGrainRain** [SyrieYume/starrail_ui#25]
默认的消息气泡、文本、头像等在我的 DPI 环境下太大了。
调整 QQNT 的字体大小并不会影响 starrail_ui 的消息气泡和头像大小。

![image](https://github.com/user-attachments/assets/fa89828c-7f3c-4603-bf16-4def6f99313b)

**Comment by yhzcake** [comment]
这个作者貌似对于这个版式有莫名的执着,建议自行通过css修改,具体怎么改可尝试使用[Transitio](https://github.com/PRO-2684/transitio)外挂css,css写法参考网络教程

**Comment by AmzGrainRain** [comment]
> 这个作者貌似对于这个版式有莫名的执着,建议自行通过css修改,具体怎么改可尝试使用[Transitio](https://github.com/PRO-2684/transitio)外挂css,css写法参考网络教程

我找到插件目录，然后修改了相关 CSS，现在在我的电脑上，效果还不错
