### ISSUE TITLE
[BUG] 深色模式下看不清消息

### ISSUE THREAD

**Issue by QingFeng-awa** [SyrieYume/starrail_ui#4]
问题描述见标题
![image](https://github.com/SyrieYume/starrail_ui/assets/151742581/a82eb6df-8b0d-4518-b981-6bc27ba5733e)

![image](https://github.com/SyrieYume/starrail_ui/assets/151742581/8a9a3f7e-963c-4bdd-894a-20097ff74b22)
上面两张图是深浅模式对比图,第一张是深色,第二张浅色

**Comment by QingFeng-awa** [comment]
靠,我没看到v0.1.1 Releases了

**Comment by QingFeng-awa** [comment]
v0.1.1没适配：（

**Comment by SyrieYume** [comment]
这应该是其它插件导致的，你安装了哪些别的插件？

**Comment by QingFeng-awa** [comment]
[LiteLoader] Start finding all plugins.
[LiteLoader] Found plugin: QQ纯享模式
[LiteLoader] Found plugin: QQCleaner
[LiteLoader] Found plugin: DeepL
[LiteLoader] Found plugin: 演示模式
[LiteLoader] Found plugin: 使用自定义浏览器打开链接并跳过拦截页
[LiteLoader] Found plugin: Euphony
[LiteLoader] Found plugin: Fake Message
[LiteLoader] Found plugin: Link Preview
[LiteLoader] Found plugin: 插件列表查看
[LiteLoader] Found plugin: 轻量工具箱
[LiteLoader] Found plugin: LLAPI
[LiteLoader] Found plugin: Markdown-it
[LiteLoader] Found plugin: 本地查看图片和视频
[LiteLoader] Found plugin: QQ消息修改
[LiteLoader] Found plugin: More Materials
[LiteLoader] Found plugin: pURLfy
[LiteLoader] Found plugin: 二维码解析
[LiteLoader] Found plugin: Scriptio
[LiteLoader] Found plugin: Transitio
[LiteLoader] Found 19 plugins, start loading plugins.

**Comment by SyrieYume** [comment]
测试了一下，是Markdown-it这个插件的问题，关掉这个插件就行了
等下个版本我会适配一下

**Comment by QingFeng-awa** [comment]
好的
