### ISSUE TITLE
[BUG] 似乎错误的隐藏了部分图标

### ISSUE THREAD

**Issue by QingFeng-awa** [SyrieYume/starrail_ui#6]
群聊更多设置里的`分享`和`邀请`图标不应该始终保持显示吗?
![image](https://github.com/SyrieYume/starrail_ui/assets/151742581/7caccc7c-c48a-4cb0-a63c-fb52f0d07124)

![image](https://github.com/SyrieYume/starrail_ui/assets/151742581/eb7ebf57-c7df-4abc-b530-b387494c6d10)

> 还有`查看群成员`文字右面的那个箭头也被隐藏了。

**Comment by SyrieYume** [comment]
鼠标移动到区域外的时候才会导致图标被隐藏，影响不大。等下个版本改一下。
