### ISSUE TITLE
消息可读性太差，是否能在配置文件中修改

### ISSUE THREAD

**Issue by LG3418** [SyrieYume/starrail_ui#7]
![dabc15be051ce56b7665d779d5843dba](https://github.com/SyrieYume/starrail_ui/assets/51922165/ddf1d8a0-e686-4bab-ba2d-8d5fb2be4076)

可能是消息行距太宽？或者是气泡字体过大？
配置文件中是否能修改这些值，现实的内容太少了，大大降低了消息的可读性

**Comment by SyrieYume** [comment]
因为在星穹铁道的短信里，气泡和字体大小就是这么大。
我在做这个主题的时候，是以全屏状态的QQ为准的。QQ窗口太小的话，一页显示的内容就很少，而且因为QQ下方输入框的原因，能显示的内容就更少了。
不过，QQ这里消息与消息之间的间距确实比星穹铁道的大一点，这个我在下版本调小一点。
你可以把Windows显示设置里的缩放调小一点，这样界面可以显示更大区域（但是气泡和字体会更小）。
