### ISSUE TITLE
希望能够自定义更多内容

### ISSUE THREAD

**Issue by Lumine139637659** [SyrieYume/starrail_ui#8]
如左侧群聊列表界面，在默认黑色调背景图、默认黑色衬底、默认黑色字体下难以阅读，希望背景可以轮播文件夹图片，最好插件的所有改动都可以自行选择是否生效

**Comment by SyrieYume** [comment]
1. 不管是夜间模式还是白天模式，左侧列表里的字体都是白色，不是黑色，检查一下是不是你安装的其它插件覆盖了样式。
2. 背景轮播的功能可以考虑添加，预计在后续版本发布。
3. 插件的功能更新会加在设置项里，但是一些对样式的小调整不会放在设置项中。每个改动都加一个设置项不现实，不仅代码上很难实现，而且会让设置页面变得很复杂。如果你想自己修改一些边距，大小，可以直接修改 src/style.css 文件, 里面有比较详细的注释。
