### ISSUE TITLE
[Bug] 插件设置页中文本框边框不清晰

### ISSUE THREAD

**Issue by adproqwq** [SyrieYume/starrail_ui#9]
rt，插件设置页中的input文本输入框，插件开发者没有另写样式时，会导致看不清边框。当文本框为空时且无placeholder时容易错误判断此处为空白。
![d823da608e0821da789054b8e4d13ab4](https://github.com/SyrieYume/starrail_ui/assets/101449500/727b5ae0-7e0d-40e6-a1d9-64679cf9f2d5)

本主题所有设置均为默认。

**Comment by SyrieYume** [comment]
这不是我的插件的问题，我没有修改插件设置页面里元素的样式，input的默认样式就是这样。

**Comment by adproqwq** [comment]
> 这不是我的插件的问题，我没有修改插件设置页面里元素的样式，input的默认样式就是这样。

好吧
